apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../../config/crd
  - ../../../config/rbac
  - ../../../config/manager

patches:
  - path: delete-namespace.yaml
    target:
      kind: Namespace
      name: mongodb-operator-system
