---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: mongodb-operator-controller-manager
    namespace: mongodb-operator-system
