---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-operator-controller-manager
  namespace: mongodb-operator-system
  labels:
    app.kubernetes.io/name: mongodb-operator
    app.kubernetes.io/component: controller-manager
