# Artifact Hub repository metadata
# https://artifacthub.io/docs/topics/repositories/

repositoryID: 386b6255-6da7-4a73-8fc0-a8e79e3c7b90

owners:
  - name: eightynine01
    email: support@keiailab.com
