apiVersion: mongodb.keiailab.com/v1alpha1
kind: MongoDB
metadata:
  name: test-rs
  namespace: mongodb-test
spec:
  members: 3
  replicaSetName: rs0
  version:
    version: "7.0"
  storage:
    size: 5Gi
  auth:
    mechanism: SCRAM-SHA-256
    adminCredentialsSecretRef:
      name: test-rs-admin-credentials
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
