apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/mongodb.keiailab.com_mongodbs.yaml
  - bases/mongodb.keiailab.com_mongodbshardeds.yaml
  - bases/mongodb.keiailab.com_mongodbbackups.yaml
